export const USER_ID_KEY: string = "user";
export const DEFAULT_AUTHORIZATION_HEADER: string = "authorization";
export const API_GATEWAY_AUTHORIZATION_HEADER: string = "x-apigateway-api-userinfo";

export const USER_ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  ADMIN: "ADMIN",
  WEB_MASTER: "WEB_MASTER",
  AUTHOR: "AUTHOR",
  EDITOR: "EDITOR",
  REVIEWER: "REVIEWER",
  COLLABORATOR: "COLLABORATOR",
  MEDIA_AUTHOR: "MEDIA_AUTHOR",
  ANALYST: "ANALYST",
  ANALYST_VISITOR: "ANALYST_VISITOR",
};

export const MEMBERSHIPS = {
  FREE: "FREE",
  NEWLETTER_ONLY: "NEWLETTER_ONLY",
  STANDARD: "STANDARD",
  PREMIUM: "PREMIUM",
};

export const MEMBERS_ROLES = {
  MEMBERSHIP_ADMIN: "MEMBERSHIP_ADMIN",
  ANALYST: "ANALYST",
};
